### ISSUE TITLE
Straff för dumma låtar

### ISSUE THREAD

**Issue by adamtornkvist** [SSundstrom/DWIMS#1]
Man borde få minuspoäng om man väljer en låt som ingen kan. Blir trött på folk som väljer så konstiga låtar som ingen hört bara för att de gillar de själva. Minus 30 poäng eller bara nollställ poängen helt. Fuck those people.

**Comment by mlonn** [comment]
![image](https://user-images.githubusercontent.com/6651453/53736226-6e17b580-3e89-11e9-8363-96149f39ef6c.png)
Nu går det att ställa in hur hårt straff en sådan spelare ska få
